#!/bin/sh

set -o errexit
set -o nounset


celery flower \
    --app=halo_leaderboards.taskapp \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
